README.md
Closes #15 
<summary>
<b>Feature</b>
</summary>
Add logo on top of readme
</details>
=> Add logo on top of readme

CONTRIBUTING.md
Criado o Contribution Guideline usando o do octopost de base
=> Contribution Guideline - Issue 12

CONTRIBUTING.md
* Criado o Contribution Guideline usando o do octopost de base
* Contribution Guideline - Issue 12
Closes 
<summary>
<b>Feature</b>
</summary>
N/A
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> Contribution Guideline - Issue 12 (#21)

docker-compose.yml
Closes #61
<summary>
<b>Feature</b>
</summary>
Configurando o docker compose fazendo a mudanca de postgres para MariaDB.
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> Trocar Banco de dados para MariaDB no docker-compose 

.env.example, api/controllers/pet/find.go, api/main.go, api/routes/routes.go, cmd/main.go, entity/pet.go, infra/db/pet_repository.go, interfaces/pet_repository.go, usecase/pet.go
Closes #38 
<summary>
<b>Feature</b>
</summary>
mostrar o pet disponivel para adoção
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
fiz junto com o lefel na talk
</details>
=> Endpoint para mostrar o pet para adoção

Dockerfile
Closes #25
Closes #26 
<summary>
<b>Feature</b>
</summary>
Adiciona dockerfile com build multi-stage
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> Adiciona Dockerfile com mult-staged build

.air.toml, .env.example, .gitignore, CONTRIBUTING.md, Dockerfile, Makefile, docker-compose.yml
Closes 
Issue #27
<summary>
<b>Feature</b>
</summary>
Docker Compose configuration for:
- Volumes and networks
- Services for live reloading, production API, database and cache
- Parameterization with environment variables
Documentation:
- Explained how to run the project for development
- Add new make commands related to running the project
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> feat: docker compose configuration

api/main.go, docs/infra/infra.md, infra/config/config.go, infra/config/logger.go
Closes #92 
<summary>
<b>Feature</b>
</summary>
Essa feature cria um logger para aplicação
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> feat: create logger

api/controllers/pet.go, api/main.go, entity/dto/pet_updade.dto.go, entity/pet.go, infra/db/pet_repository.go, interfaces/pet_repository.go, usecase/pet.go, usecase/pet_test.go
Closes #59
<summary>
<b>Feature</b>
</summary>
Adicionando o update de vacinas e modificada a entidade pet
N/A
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> [UPDATE PET] Incluir campo de Vacinas (array de vacina tipo, data e nome do doutor) #59

api/controllers/pet.go, api/routes/routes.go, entity/dto/pet_insert_dto.go, entity/pet.go, infra/db/pet_repository.go, usecase/pet.go, usecase/pet_test.go
Closes #42 
<summary>
<b>Feature</b>
</summary>
Cria a rota para cadastrar pet com Nome, Id da raça e Id do usuário
</details>
<summary>
</summary>
Nenhum.
</details>
<summary>
</summary>
</details>
<summary>
</summary>
N/A
</details>
=> Cadastro de pet

api/controllers/user.go, api/routes/routes.go, entity/dto/user_update.dto.go, infra/db/user_repository.go, usecase/breed.go, usecase/pet_test.go, usecase/user.go, usecase/user_test.go
Closes #31 
<summary>
<b>Feature</b>
</summary>
Desenvolvido o endpoint para atualizar campos do usuário de acordo com a tela de configuração do usuário do protótipo.
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> Desenvolver endpoint de atualizar usuário #31

api/controllers/breed.go, api/routes/routes.go, infra/db/breed_repository.go, interfaces/breed_repository.go, usecase/breed.go, usecase/breed_test.go
Closes #128 
<summary>
<b>Feature</b>
</summary>
Adiciona endpoint GET de Breed por ID, utilizando a função criada de FindByID do usecase de Breed.
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> Issue 128 - Rota de Pegar uma unica breed

usecase/breed.go, usecase/ong.go, usecase/pet.go
Closes #140 
<summary>
<b>Feature</b>
</summary>
N/A
</details>
<summary>
<b>Bugfix</b>
</summary>
Usecase com ultilização de logs de forma incorreta.
- **Cause**
N/A
- **Solution**
Utilização dos logs nos seguintes useacases (breed, pet e ong)
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> Atualização da ultilização dos logs

compose.yml
Closes 
<summary>
<b>Feature</b>
</summary>
N/A
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> fix: ajust port bind on api

api/controllers/pet.go, api/routes/routes.go, entity/pet.go, infra/db/pet_repository.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #168 
<summary>
<b>Feature</b>
</summary>
- refactor: alteração do param `id`para `petID` para padronização com outras rotas.
- fix: correção de script SQL de `pet_repository.go` corrigi incompatibilidade de campos de consulta. Erro que estava sendo retornado  `Error 1054 (42S22): Unknown column 'p.needed' in 'field list'`.
Alterações realizadas: `p.neede` foi alterado para `p.neededSpecialCare`. Além desse, outro campo foi alterado, mas estou detalhando apenas um para contextualização.
- fix: correção de quantidade de número de parâmetros declarados. Ao tentar realizar consulta, o seguinte erro foi retornado:  `failed to retrieve pet: error scanning pet: sql: expected 16 destination arguments in Scan, not 14`
O erro aconteceu devido a ausência de dois campos no …
=> Criação da rota para busca de pet por ID e documentação da mesma com swag #168

api/controllers/pet.go, api/routes/routes.go, entity/dto/pet_update.dto.go, entity/pet.go, infra/db/pet_repository.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #175 
<summary>
<b>Feature</b>
</summary>
- feat: documentação da rota PATCH pet
- fix: recuperando rota de atualização de pet excluído no merge: [**[Listar pets do usuário #67](https://github.com/devhatt/pet-dex-backend/pull/67/files)**]
- fix: correção de inconsistência de propriedade declarada no PetUpdateDto com banco de dados
- fix: alteração das tags json para consistência no envio e recebimento de dados pelo DB.
</details>
<summary>
<b>Bugfix</b>
</summary>
TÓPICO: recuperando rota de atualização de pet excluído no merge
Durante o processo de documentação do endpoint … identificou-se a ausência da rota responsável pelo PATCH contendo {userID} e {petID}. Uma verificação nos commits, foi identificado que a rota que fornecia …
=> issue: documentação da rota pet PATCH (#175)

api/controllers/pet.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #179 
<summary>
<b>Feature</b>
</summary>
Foi adicionado documentação para listagem de todos os pets na rota pública /pets/
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
Imagem do retorno da documentação com informações do pet atualmente cadastrado em meu ambiente de desenvolvimento.
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> feat: adiciona documentação na rota pública pets

api/controllers/pet.go, api/routes/routes.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #169 
<summary>
<b>Feature</b>
</summary>
Documentação da rota meus pets
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> feat: my pets swagger

api/controllers/breed.go, entity/dto/breed_list.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #177 
<summary>
<b>Feature</b>
</summary>
* Adiciona documentação para a rota api/breeds/
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> feat: documentação rota /api/pets/breeds/ GET # issue-177

.tool-versions, api/controllers/user.go, entity/dto/user_insert.dto.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes  #174 
<summary>
<b>Feature</b>
</summary>
Adiciona rota de cadastro de usuário
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> feat: swagger user create

api/controllers/user.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #178 
<summary>
<b>Feature</b>
</summary>
Doc do login 
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> docs: create login doc

api/controllers/ong.go, entity/dto/link_dto.go, entity/dto/ong_list_dto.go, entity/dto/ong_update_dto.go, infra/db/ong_repository.go, interfaces/ong_repository.go, mocks/pet-dex-backend/v2/interfaces/mock_OngRepository.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml, usecase/ong.go, usecase/ong_test.go
Closes #184 
<summary>
<b>Feature</b>
</summary>
Adiciona a documentação para a rota `/ongs/{ongID} [get]`, e altera o response dela para `dto.OngListMapper` 
(Essa parte da ONG está bem confusa. Seria bom conferir os campos que ela deveria retornar e criar uma task, se necessário)
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> docs: Ong FindByID

Makefile, api/controllers/ong.go, swagger/details.md, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #180 
<summary>
<b>Feature</b>
</summary>
Implementação da documentação para rota  api/ongs/ [get]
* Mudança no arquivo makefile para geração de doc a partir de notação markdown.
* Uso de notação markdown para melhoria da doc
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> feat: doc api/ongs/ GET 

api/controllers/user.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #176 
<summary>
<b>Feature</b>
</summary>
Documentação de rota de login de usuário por SSO
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> docs: create login with SSO doc

api/controllers/ong.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes  #182 
<summary>
<b>Feature</b>
</summary>
Adicionada documentação de deletar ONG por ID.
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
=> feat: ong delete doc

api/controllers/user.go, api/routes/routes.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #170 
<summary>
<b>Feature</b>
</summary>
Adicionar rota para buscar usuario por ID
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> Issue 170 - Adicionar documentação na rota de GetById do usuario

pkg/mail/README.md
Closes  #121 
<summary>
<b>Feature</b>
</summary>
Adicionada documentação do pacote de email
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
=> feat: mail pkg

api/controllers/user.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #185 
<summary>
<b>Feature</b>
</summary>
create push notifications doc
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> docs: create push notifications doc

api/controllers/ong.go, entity/dto/ong_insert_dto.go, entity/ong.go, infra/db/ong_repository.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #181 
<summary>
<b>Feature</b>
</summary>
* Implementação da documentação para a rota Ongs POST.
* Correção de limitação da geração de documentação por causa do tipo RawMessegeJson.
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> feat: documentação da rota api/ongs POST

api/controllers/user.go, api/routes/routes.go, swagger/docs.go, swagger/swagger.json, swagger/swagger.yaml
Closes #172 
<summary>
<b>Feature</b>
</summary>
N/A
</details>
<summary>
<b>Bugfix</b>
</summary>
N/A
- **Cause**
N/A
- **Solution**
N/A
</details>
<details> 
<summary>
</summary>
N/A
</details>
<summary>
</summary>
</details>
<summary>
</summary>
</details>
<details> 
<summary>
</summary>
N/A
</details>
=> docs: create delete user by id doc
